#!/usr/bin/env python3
"""Install a pre-commit hook that runs the gate. Opt-in, and idempotent.

WHY THIS EXISTS, MEASURED RATHER THAN ANTICIPATED

RULES 10.3 requires the gate green at every commit. On 2026-09-08 two commits
were pushed red, both the same way and neither through carelessness about the
rule:

    the gate was run, it passed, one more edit landed, and the reading was
    not repeated.

Both were caught -- once by CI, once by a cold-start review -- and both cost a
follow-up commit. A rule that depends on remembering to re-read after the last
edit is a rule that fails exactly when a session is busiest.

⛔ **IT IS NOT INSTALLED AUTOMATICALLY.** A hook is a change to somebody's
working copy that outlives the session, and `docs/agent-tooling.md` names
installing things as the first reflex to stop. Run it deliberately:

```sh
python3 scripts/install-hooks.py
```

⚠ **And it is `--fast` by design.** The full gate takes tens of seconds because
it runs the suite and two end-to-end generations, and a pre-commit hook that
slow is one people bypass with `--no-verify`, which leaves them worse off than
no hook. `--fast` catches every failure both of this session's red commits had:
a stale count, a marker outside the five, an entry that disagrees with its
index row. ⛔ **It is not a verdict on the tree** -- `gate.md` says so -- and the
hook prints that.

Exit codes:
    0  installed, or already current
    1  refused: not a git repository, or a different hook is in the way
    2  could not run
"""

from __future__ import annotations

import os
import stat
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _scope  # noqa: E402 - reconfigures stdout on import

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MARKER = "# trackers pre-commit hook v1"
HOOK = f"""#!/bin/sh
{MARKER}
# RULES 10.3: the gate passes at every commit. Regenerated by
# scripts/install-hooks.py; delete this file to remove it.
#
# --fast, deliberately: the full gate runs the suite and two end-to-end
# generations, and a hook that slow gets bypassed. This is not a verdict on the
# tree -- run `python3 scripts/check-gate.py` before pushing.
# PROBE BY RUNNING, NOT BY FINDING. `command -v python3` succeeds on a Windows
# host where python3 is a Microsoft Store stub that exits without running --
# docs/conventions/shell.md section 6, measured, and this hook walked into it
# on the day it was written.
if python3 -c "" >/dev/null 2>&1; then PY=python3
elif python -c "" >/dev/null 2>&1; then PY=python
else echo "pre-commit: no working python on PATH"; exit 1; fi
"$PY" "$(git rev-parse --show-toplevel)/scripts/check-gate.py" --fast || {{
    echo ""
    echo "pre-commit: the fast gate failed. Fix it, or commit with --no-verify"
    echo "if you know why and are about to fix it in the next commit."
    exit 1
}}
"""


def main() -> int:
    git_dir = os.path.join(REPO, ".git")
    if not os.path.isdir(git_dir):
        print("not a git repository (no .git directory)", file=sys.stderr)
        return 1
    hooks = os.path.join(git_dir, "hooks")
    os.makedirs(hooks, exist_ok=True)
    path = os.path.join(hooks, "pre-commit")

    if os.path.exists(path):
        with open(path, encoding="utf-8", errors="replace") as fh:
            existing = fh.read()
        if MARKER not in existing:
            # ⛔ Never overwrite somebody else's hook. A tool that silently
            # replaces a file it did not write is the destructive shape this
            # repository refuses everywhere else.
            print(f"{path} exists and is not ours; refusing to overwrite it.",
                  file=sys.stderr)
            print("Move it aside and re-run, or add the gate call yourself.",
                  file=sys.stderr)
            return 1
        if existing == HOOK:
            print("pre-commit hook is already current.")
            return 0

    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HOOK)
    os.chmod(path, os.stat(path).st_mode | stat.S_IXUSR | stat.S_IXGRP)
    print(f"installed {os.path.relpath(path, REPO)}")
    print("it runs `check-gate.py --fast`; delete the file to remove it.")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except OSError as exc:
        print(f"install-hooks: {exc}", file=sys.stderr)
        sys.exit(2)
