"""The source registry: one structured place where every source difference lives.

T-100 requires source-specific behaviour not to be scattered through
the codebase, and -- equally -- warns against building "a plugin framework for
six sources", which "costs more than it saves and is a common way this kind of
project becomes unmaintainable". So this is a table of dataclasses, not a
plugin system. Adding a source is adding a row.

The `role` field is not decoration and was not in the original brief. It exists
because `experiments/19` shipped a methodology bug without it: unique-contribution
was computed with `pkgforge_all` in the comparison set, and `pkgforge_all` is a
**strict superset** of `desirefire_all` (1091 of 1091 entries, measured). The
result was that the largest unique contributor in the corpus reported as
contributing **zero**. Comparing a source against its own downstream copy
always shows redundancy, so the role has to be modelled.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class Role(str, Enum):
    """What kind of thing a source is. Decides how its entries may be counted."""

    #: Has its own upstream. Counts toward the dataset and toward unique
    #: contribution.
    PRIMARY = "primary"

    #: Generated by combining other sources in this registry. Counts toward the
    #: dataset, but MUST be excluded from unique-contribution arithmetic.
    DERIVATIVE = "derivative"

    #: A list of trackers an upstream deliberately REMOVED. Its entries must
    #: never be counted as available trackers -- that would invert their
    #: meaning -- but its reasons are evidence worth publishing.
    BLACKLIST = "blacklist"


class Trust(str, Enum):
    """How much weight this source's mere presence carries.

    Deliberately coarse. T-044 warns against precision applied to the
    wrong quantity, and a finely-graded trust score over six sources would be
    exactly that.
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


#: The one method any band in this registry is derived by, named so that a
#: reader can check the arithmetic rather than trust the number.
WIDE_BAND = "0.4x the smallest observation to 3x the largest, rounded outward"


@dataclass(frozen=True, slots=True)
class Derivation:
    """Where a source's expected band came from. T-102.

    ⛔ **A threshold with no derivation is a magic number, and a magic
    number nobody can justify is a future outage.** The band used to be two
    integers beside a comment saying they were "~40% and ~3x" of one
    observation -- and two of the eight did not actually satisfy that rule,
    by one entry each. Numbers typed beside a stated method drift from it
    silently, which is RULES 2.1 at miniature scale.

    ⭐ **So the derivation is the authority and the band is checked against
    it.** `tests/test_thresholds.py` fails when a registry band is narrower than
    what its own observations support, which is the direction T-102's
    `Decision` fixes: widen rather than narrow while the sample is small.
    """

    #: The counts actually seen, oldest first. One today, for every source.
    observations: tuple[int, ...]
    #: The instants those counts were taken at, one per observation.
    window: tuple[str, ...]
    #: The committed script that measured them. RULES 2: the instrument is the
    #: deliverable, and a number without one is not a number.
    instrument: str
    method: str = WIDE_BAND

    @property
    def samples(self) -> int:
        return len(self.observations)

    def derived_band(self) -> tuple[int, int]:
        """The narrowest band `method` justifies from these observations.

        ⚠ **Narrowest, not the band in use.** The registry may be wider --
        it usually is, because a small source's natural variation is larger
        than a multiple of a small number -- and wider is always permitted.
        Narrower is not, and that is what the test enforces.
        """
        low = max(1, int(0.4 * min(self.observations)))
        high = int(3 * max(self.observations)) + 1
        return (low, high)


#: ⛔ **One parser, and the registry says so rather than implying it.**
#: T-100's `Decision` forbids a plugin framework for eight sources: every one
#: of them is newline-ish plaintext today and `normalize.parse_many` handles
#: all of them. Naming it per source is what makes a future exception visible
#: as a change to this table instead of as a branch buried in the fetcher.
ONE_PARSER = "normalize.parse_many"

#: The fetch strategy every source shares. T-104 made conditional requests
#: mandatory in `ci`, so this is a statement of what the code does and not an
#: aspiration.
CONDITIONAL_GET = "conditional GET, If-None-Match and If-Modified-Since"

#: The cache strategy every source shares: one snapshot per source, with the
#: validators the server offered, so the next run can take a 304.
SNAPSHOT_CACHE = "one snapshot per source id, with its validators"

#: ⚠ **No source needs its own normalization, and that is a measured
#: claim rather than a default.** `experiments/19` parses every source through
#: the one parser and reports the unparseable lines per source; they are the
#: same rejects everywhere. A source that grows a quirk gets a value here and
#: the table shows it.
NO_SPECIAL_NORMALIZATION = "none; the common normalizer handles it"

#: The validation every fetched body goes through, in the order `acquire.py`
#: applies it. ⛔ A rule listed here that nothing runs would be dead
#: config, so this names the checks in `parse_body` and `validate_counts`.
COMMON_VALIDATION = (
    "not HTML",
    "parses to at least one tracker",
    "entry count inside the derived band",
)


@dataclass(frozen=True, slots=True)
class Source:
    """One source. Every field is something that differs between sources."""

    id: str
    url: str
    role: Role
    trust: Trust
    category: str
    upstream: str
    notes: str

    #: Expected entry-count range, used by the change detector (T-102).
    #: ⛔ **Every band carries its derivation** and a test fails when one
    #: is narrower than its own observations support. They stay wide on
    #: purpose: the window is **one observation** for every source, and one
    #: sample cannot justify a narrow band. Widening as evidence arrives is
    #: safe; narrowing on one sample is the outage T-102 exists to prevent.
    expected_min: int
    expected_max: int
    derivation: "Derivation"

    #: T-100. The static description of how this source is handled. ⚠ The
    #: entry's `Premise` is what decides which fields belong here: **last
    #: successful fetch, last failure, failure count and health state are
    #: per-run state, not configuration**, so they live in
    #: `provenance.SourceHistory` on the `data` branch (T-103) and are not
    #: duplicated into this table. A value in two places with no check that
    #: they agree is drift, and the copy a reader trusts is the wrong one.
    expected_format: str = "newline-delimited tracker URLs, blank lines and "\
                           "`#` comments permitted"
    parser: str = ONE_PARSER
    fetch_strategy: str = CONDITIONAL_GET
    cache_strategy: str = SNAPSHOT_CACHE
    normalization: str = NO_SPECIAL_NORMALIZATION
    validation_rules: tuple[str, ...] = COMMON_VALIDATION

    @property
    def observed(self) -> int:
        """The most recent observed count, for a message that has to name one."""
        return self.derivation.observations[-1]

    @property
    def observed_at(self) -> str:
        return self.derivation.window[-1]

    #: Whether a fetch failure for this source should block publication.
    #: False for every source: RULES 3.10 requires that one failing source
    #: never fails the others.
    required: bool = False
    enabled: bool = True


#: The registry. Every count in a `Derivation` is measured by the
#: instrument it names, not estimated. ⚠ `ngosang_all` and
#: `xiu2_all` were **one entry narrower** than the rule their comment
#: stated until 2026-09-09; they are widened to contain it, because a
#: band that disagrees with its own derivation is the number nobody can
#: justify that T-102 is about.
SOURCES: tuple[Source, ...] = (
    Source(
        id="ngosang_all",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt",
        role=Role.PRIMARY, trust=Trust.HIGH, category="general",
        upstream="ngosang/trackerslist",
        notes=(
            "The most widely consumed public list. NOTE, measured: this file "
            "is udp+http+https ONLY (48+37+14=99) and silently excludes every "
            "ws, i2p and yggdrasil entry. Consuming it alone loses 17 trackers "
            "across three networks. Its generator is NOT published, so its "
            "'sorted by popularity and latency' ordering is unauditable "
            "(C-22); we therefore take its CONTENT and not its ORDER."
        ),
        expected_min=39, expected_max=300, derivation=Derivation(observations=(99,),
                              window=("2026-08-29",),
                              instrument="experiments/19-scheme-census.py"),
    ),
    Source(
        id="ngosang_ws",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ws.txt",
        role=Role.PRIMARY, trust=Trust.HIGH, category="webtorrent",
        upstream="ngosang/trackerslist",
        notes=(
            "The only source of WebSocket trackers in the corpus. Scheme is "
            "`wss`, not `ws` -- `ws` occurs zero times across the census union, "
            "and the corpus's single `ws://` URL is a blacklisted one."
        ),
        expected_min=1, expected_max=40, derivation=Derivation(observations=(3,),
                              window=("2026-08-29",),
                              instrument="experiments/19-scheme-census.py"),
    ),
    Source(
        id="ngosang_i2p",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_i2p.txt",
        role=Role.PRIMARY, trust=Trust.HIGH, category="i2p",
        upstream="ngosang/trackerslist",
        notes=(
            "Schemes present are http and udp -- .i2p is a HOSTNAME SUFFIX, "
            "not a scheme. This is the source that forced the transport x "
            "network model. Unmeasurable from this vantage, published as such."
        ),
        expected_min=1, expected_max=60, derivation=Derivation(observations=(13,),
                              window=("2026-08-29",),
                              instrument="experiments/19-scheme-census.py"),
    ),
    Source(
        id="ngosang_yggdrasil",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_yggdrasil.txt",
        role=Role.PRIMARY, trust=Trust.HIGH, category="yggdrasil",
        upstream="ngosang/trackerslist",
        notes=(
            "One entry, addressed by HOSTNAME (yggtracker.i2p.rocks), which a "
            "URL-only classifier necessarily reads as clearnet. Yggdrasil "
            "detection needs DNS; see model.classify_network's limitation note."
        ),
        expected_min=1, expected_max=30, derivation=Derivation(observations=(1,),
                              window=("2026-08-29",),
                              instrument="experiments/19-scheme-census.py"),
    ),
    Source(
        id="ngosang_blacklist",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/blacklist.txt",
        role=Role.BLACKLIST, trust=Trust.HIGH, category="exclusion",
        upstream="ngosang/trackerslist",
        notes=(
            "346 entries with reasons attached. Never counted as available "
            "trackers. The reasons are evidence: 2 are 'requested by sysadmin', "
            "which is direct support for RULES 4's exclusion requirement."
        ),
        # ⛔ The one source whose FORMAT differs, and the difference is
        # load-bearing: a blacklist's exclusion REASONS live in its raw text
        # and the ordinary parser strips them, so a caller that reads only the
        # parsed URLs cannot tell an operator's request from an upstream's
        # opinion. That is exactly the defect that published eight excluded
        # URLs on 2026-09-09, and naming the format here is what stops the next
        # reader assuming every source is interchangeable.
        expected_format=("newline-delimited tracker URLs with `#` comment "
                         "lines carrying the exclusion REASON, which the "
                         "common parser strips and `exclusion.py` needs"),
        expected_min=100, expected_max=1200, derivation=Derivation(observations=(346,),
                              window=("2026-08-29",),
                              instrument="experiments/19-scheme-census.py"),
    ),
    Source(
        id="newtrackon_all",
        url="https://newtrackon.com/api/all",
        role=Role.PRIMARY, trust=Trust.HIGH, category="general",
        upstream="CorralPeltzer/newTrackon",
        notes=(
            "Equivalent to /api/0. Entries are BLANK-LINE separated (measured: "
            "156 lines, 78 non-blank, 78 blank on /api/live). Also our ORACLE: "
            "/api/<int:percentage> exposes uptime, but that uptime is "
            "ANNOUNCE-derived while ours is scrape-derived, so the two answer "
            "different questions and must not be silently compared."
        ),
        expected_min=100, expected_max=800, derivation=Derivation(observations=(261,),
                              window=("2026-08-29",),
                              instrument="experiments/19-scheme-census.py"),
    ),
    Source(
        id="xiu2_all",
        url="https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt",
        role=Role.PRIMARY, trust=Trust.MEDIUM, category="general",
        upstream="XIU2/TrackersListCollection",
        notes=(
            "Trust is MEDIUM on the maintainer's own statement: its workflow "
            "header records that after migrating to Actions 'the filtering "
            "process has been temporarily streamlined'. Contributed 8 unique "
            "URLs of 150 against other primaries."
        ),
        expected_min=60, expected_max=460, derivation=Derivation(observations=(150,),
                              window=("2026-08-29",),
                              instrument="experiments/19-scheme-census.py"),
    ),
    Source(
        id="desirefire_all",
        url="https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt",
        role=Role.PRIMARY, trust=Trust.LOW, category="anime",
        upstream="DeSireFire/animeTrackerList",
        notes=(
            "Last upstream push 2024-01-12, ~2.6 years stale, and BY FAR the "
            "largest unique contributor: 995 unique of 1091. Trust is LOW "
            "because staleness is measured and liveness of those 995 is NOT "
            "yet measured -- uniqueness and value are different claims. Do not "
            "drop it on staleness alone and do not promote it on uniqueness "
            "alone."
        ),
        expected_min=400, expected_max=3300, derivation=Derivation(observations=(1091,),
                              window=("2026-08-29",),
                              instrument="experiments/19-scheme-census.py"),
    ),
)

#: Sources whose entries may be counted toward the published dataset.
PUBLISHABLE_ROLES: frozenset[Role] = frozenset({Role.PRIMARY, Role.DERIVATIVE})

#: Sources that may be compared for unique contribution (T-101).
COMPARABLE_ROLES: frozenset[Role] = frozenset({Role.PRIMARY})


def by_id(source_id: str) -> Source:
    for s in SOURCES:
        if s.id == source_id:
            return s
    raise KeyError(f"no such source: {source_id!r}")


def enabled_sources() -> tuple[Source, ...]:
    return tuple(s for s in SOURCES if s.enabled)
