"""The source registry: one structured place where every source difference lives.

T-100 requires source-specific behaviour not to be scattered through
the codebase, and -- equally -- warns against building "a plugin framework for
six sources", which "costs more than it saves and is a common way this kind of
project becomes unmaintainable". So this is a table of dataclasses, not a
plugin system. Adding a source is adding a row.

The `role` field is not decoration and was not in the original brief. It exists
because `experiments/19` shipped a methodology bug without it: unique-contribution
was computed with `pkgforge_all` in the comparison set, and `pkgforge_all` is a
**strict superset** of `desirefire_all` (1091 of 1091 entries, measured). The
result was that the largest unique contributor in the corpus reported as
contributing **zero**. Comparing a source against its own downstream copy
always shows redundancy, so the role has to be modelled.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class Role(str, Enum):
    """What kind of thing a source is. Decides how its entries may be counted."""

    #: Has its own upstream. Counts toward the dataset and toward unique
    #: contribution.
    PRIMARY = "primary"

    #: Generated by combining other sources in this registry. Counts toward the
    #: dataset, but MUST be excluded from unique-contribution arithmetic.
    DERIVATIVE = "derivative"

    #: A list of trackers an upstream deliberately REMOVED. Its entries must
    #: never be counted as available trackers -- that would invert their
    #: meaning -- but its reasons are evidence worth publishing.
    BLACKLIST = "blacklist"


class Trust(str, Enum):
    """How much weight this source's mere presence carries.

    Deliberately coarse. T-044 warns against precision applied to the
    wrong quantity, and a finely-graded trust score over six sources would be
    exactly that.
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass(frozen=True, slots=True)
class Source:
    """One source. Every field is something that differs between sources."""

    id: str
    url: str
    role: Role
    trust: Trust
    category: str
    upstream: str
    notes: str

    #: Expected entry-count range, used by the change detector (T-102).
    #: **These are provisional and marked as such**, per T-102: "Thresholds MUST
    #: be derived from observed source behaviour, not invented. Until enough
    #: history exists to derive them, use conservative provisional values and
    #: mark them as provisional." The lower bounds are ~40% of the single
    #: observation made on 2026-08-29 by `experiments/19`; the upper bounds are
    #: ~3x. They are wide on purpose: a narrow band nobody can justify causes
    #: outages, and one sample cannot justify a narrow band.
    expected_min: int
    expected_max: int
    observed_20260829: int

    #: Whether a fetch failure for this source should block publication.
    #: False for every source: RULES 3.10 requires that one failing source
    #: never fails the others.
    required: bool = False
    enabled: bool = True


#: The registry. Counts in `observed_20260829` are measured by
#: `experiments/19-scheme-census.py`, not estimated.
SOURCES: tuple[Source, ...] = (
    Source(
        id="ngosang_all",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt",
        role=Role.PRIMARY, trust=Trust.HIGH, category="general",
        upstream="ngosang/trackerslist",
        notes=(
            "The most widely consumed public list. NOTE, measured: this file "
            "is udp+http+https ONLY (48+37+14=99) and silently excludes every "
            "ws, i2p and yggdrasil entry. Consuming it alone loses 17 trackers "
            "across three networks. Its generator is NOT published, so its "
            "'sorted by popularity and latency' ordering is unauditable "
            "(C-22); we therefore take its CONTENT and not its ORDER."
        ),
        expected_min=40, expected_max=300, observed_20260829=99,
    ),
    Source(
        id="ngosang_ws",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ws.txt",
        role=Role.PRIMARY, trust=Trust.HIGH, category="webtorrent",
        upstream="ngosang/trackerslist",
        notes=(
            "The only source of WebSocket trackers in the corpus. Scheme is "
            "`wss`, not `ws` -- `ws` occurs zero times across the census union, "
            "and the corpus's single `ws://` URL is a blacklisted one."
        ),
        expected_min=1, expected_max=40, observed_20260829=3,
    ),
    Source(
        id="ngosang_i2p",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_i2p.txt",
        role=Role.PRIMARY, trust=Trust.HIGH, category="i2p",
        upstream="ngosang/trackerslist",
        notes=(
            "Schemes present are http and udp -- .i2p is a HOSTNAME SUFFIX, "
            "not a scheme. This is the source that forced the transport x "
            "network model. Unmeasurable from this vantage, published as such."
        ),
        expected_min=1, expected_max=60, observed_20260829=13,
    ),
    Source(
        id="ngosang_yggdrasil",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_yggdrasil.txt",
        role=Role.PRIMARY, trust=Trust.HIGH, category="yggdrasil",
        upstream="ngosang/trackerslist",
        notes=(
            "One entry, addressed by HOSTNAME (yggtracker.i2p.rocks), which a "
            "URL-only classifier necessarily reads as clearnet. Yggdrasil "
            "detection needs DNS; see model.classify_network's limitation note."
        ),
        expected_min=1, expected_max=30, observed_20260829=1,
    ),
    Source(
        id="ngosang_blacklist",
        url="https://raw.githubusercontent.com/ngosang/trackerslist/master/blacklist.txt",
        role=Role.BLACKLIST, trust=Trust.HIGH, category="exclusion",
        upstream="ngosang/trackerslist",
        notes=(
            "346 entries with reasons attached. Never counted as available "
            "trackers. The reasons are evidence: 2 are 'requested by sysadmin', "
            "which is direct support for RULES 4's exclusion requirement."
        ),
        expected_min=100, expected_max=1200, observed_20260829=346,
    ),
    Source(
        id="newtrackon_all",
        url="https://newtrackon.com/api/all",
        role=Role.PRIMARY, trust=Trust.HIGH, category="general",
        upstream="CorralPeltzer/newTrackon",
        notes=(
            "Equivalent to /api/0. Entries are BLANK-LINE separated (measured: "
            "156 lines, 78 non-blank, 78 blank on /api/live). Also our ORACLE: "
            "/api/<int:percentage> exposes uptime, but that uptime is "
            "ANNOUNCE-derived while ours is scrape-derived, so the two answer "
            "different questions and must not be silently compared."
        ),
        expected_min=100, expected_max=800, observed_20260829=261,
    ),
    Source(
        id="xiu2_all",
        url="https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt",
        role=Role.PRIMARY, trust=Trust.MEDIUM, category="general",
        upstream="XIU2/TrackersListCollection",
        notes=(
            "Trust is MEDIUM on the maintainer's own statement: its workflow "
            "header records that after migrating to Actions 'the filtering "
            "process has been temporarily streamlined'. Contributed 8 unique "
            "URLs of 150 against other primaries."
        ),
        expected_min=60, expected_max=450, observed_20260829=150,
    ),
    Source(
        id="desirefire_all",
        url="https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt",
        role=Role.PRIMARY, trust=Trust.LOW, category="anime",
        upstream="DeSireFire/animeTrackerList",
        notes=(
            "Last upstream push 2024-01-12, ~2.6 years stale, and BY FAR the "
            "largest unique contributor: 995 unique of 1091. Trust is LOW "
            "because staleness is measured and liveness of those 995 is NOT "
            "yet measured -- uniqueness and value are different claims. Do not "
            "drop it on staleness alone and do not promote it on uniqueness "
            "alone."
        ),
        expected_min=400, expected_max=3300, observed_20260829=1091,
    ),
)

#: Sources whose entries may be counted toward the published dataset.
PUBLISHABLE_ROLES: frozenset[Role] = frozenset({Role.PRIMARY, Role.DERIVATIVE})

#: Sources that may be compared for unique contribution (T-101).
COMPARABLE_ROLES: frozenset[Role] = frozenset({Role.PRIMARY})


def by_id(source_id: str) -> Source:
    for s in SOURCES:
        if s.id == source_id:
            return s
    raise KeyError(f"no such source: {source_id!r}")


def enabled_sources() -> tuple[Source, ...]:
    return tuple(s for s in SOURCES if s.enabled)
